# Generated by Django 4.0.5 on 2022-06-28 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreservation',
            name='email',
            field=models.EmailField(max_length=250),
        ),
    ]
