# Generated by Django 4.0.5 on 2022-06-30 15:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_alter_userreservation_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='facebook',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='doctors',
            name='instagram',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='doctors',
            name='linkedin',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='doctors',
            name='twitter',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='userreservation',
            name='phone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Phone format in xxx xxx xxxx', regex='^(\\d{3}[- .]?){2}\\d{4}$')]),
        ),
    ]
