# Generated by Django 4.0.5 on 2022-07-01 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0004_about_us'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='icons',
            field=models.CharField(choices=[('Cardiology', 'fas fa-heartbeat'), ('Tablets', 'fas fa-pills'), ('Hospital', 'fas fa-hospital-user'), ('DNA-TEST', 'fas fa-dna')], default='', max_length=50),
        ),
    ]
