# Generated by Django 4.0.5 on 2022-07-01 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0008_alter_services_icons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='icons',
            field=models.CharField(choices=[('fas fa-heartbeat', 'Cardiology'), ('fas fa-pills', 'Pills'), ('fas fa-hospital-user', 'Hospital'), ('fas fa-dna', 'DNA-TEST'), ('fas fa-wheelchair', 'Disabled-person'), ('fas fa-notes-medical', 'Appointments'), ('fas fa-thermometer', 'Thermometer')], default='', max_length=50),
        ),
    ]
