# Generated by Django 4.0.5 on 2022-07-03 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0010_awards'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='awards',
            name='award',
        ),
        migrations.AddField(
            model_name='awards',
            name='awards_count',
            field=models.IntegerField(default=0),
        ),
    ]
