# Generated by Django 4.0.5 on 2022-07-03 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0011_remove_awards_award_awards_awards_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='awards',
            old_name='awards_count',
            new_name='award',
        ),
    ]
