# Generated by Django 4.0.5 on 2022-07-04 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0012_rename_awards_count_awards_award'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('positions', models.CharField(choices=[('col-lg-3 col-md-6', '1'), ('col-lg-3 col-md-6 mt-4 mt-md-0', '2'), ('col-lg-3 col-md-6 mt-4 mt-lg-0', '3'), ('col-lg-3 col-md-6 mt-4 mt-lg-0', '4')], default='', max_length=50)),
                ('option_1', models.CharField(max_length=50)),
                ('option_2', models.CharField(max_length=50)),
                ('option_3', models.CharField(max_length=50)),
                ('option_4', models.CharField(max_length=50)),
                ('option_5', models.CharField(max_length=50)),
                ('cross_out_option_1', models.CharField(choices=[('class="na"', 'Yes'), ('', 'No')], default='', max_length=50)),
                ('cross_out_option_2', models.CharField(choices=[('class="na"', 'Yes'), ('', 'No')], default='', max_length=50)),
                ('cross_out_option_3', models.CharField(choices=[('class="na"', 'Yes'), ('', 'No')], default='', max_length=50)),
                ('cross_out_option_4', models.CharField(choices=[('class="na"', 'Yes'), ('', 'No')], default='', max_length=50)),
                ('cross_out_option_5', models.CharField(choices=[('class="na"', 'Yes'), ('', 'No')], default='', max_length=50)),
            ],
        ),
    ]
