# Generated by Django 4.0.5 on 2022-07-04 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0013_pricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
