# Generated by Django 4.0.5 on 2022-07-05 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0015_alter_pricing_cross_out_option_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awards',
            name='award',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
