# Generated by Django 4.0.5 on 2022-07-06 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0018_alter_pricing_cross_out_option_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.TextField(max_length=200)),
                ('position', models.CharField(choices=[('faq1', '1'), ('faq2', '2'), ('faq3', '3'), ('faq4', '4'), ('faq5', '5'), ('faq6', '6'), ('faq7', '7'), ('faq8', '8')], max_length=50)),
                ('is_visible', models.BooleanField(default=True)),
            ],
        ),
    ]
