# Generated by Django 4.0.5 on 2022-07-06 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0019_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='desc',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='questions',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
